
spring:

  mail:
    host: smtp.gmail.com
    port: 587
    username: tjrhk01@gmail.com
    password: ftnzwqsrhbfiyrud
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  datasource:
    url: jdbc:mariadb://localhost:3306/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicam_user
    password: 1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: debug






